### ISSUE TITLE
Marcas Mundiales (/) [Think/Develop]

### ISSUE THREAD

**Issue by darwinva97** [aimet-io/landing#27]
¿Qué hacer con esta sección?

- Modificar el Componente en cuestión

![Image](https://user-images.githubusercontent.com/30082909/224449087-7bf29645-4cf3-4098-aa92-69985b74679b.png)

**Comment by EijunnN** [comment]
Ocultarlos por el momento. También sería buena idea de conversar con Maby ( la dueña del server de discord) para que nos promocione y le colocamos el link de su server o lo que desee

**Comment by PatrickCuentas** [comment]
Por ahora como dice @Eijunn no mostrarlos en mi opinión hasta que tengamos un socio seguro

**Comment by JosephVTX** [comment]
Dejarlo por el momento

**Comment by darwinva97** [comment]
@rafaelmallquii  también sugirió poner los logos de las empresas en donde tenemos actividad, en Perú sería Inversiones Sideral y en méxico la empresa de Edgar.
